/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Gesa Rizky Nugraha
 */
public class Framebanpecah extends javax.swing.JFrame {

    /**
     * Creates new form Framebanpecah
     */
    public Framebanpecah() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ina = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inb = new javax.swing.JTextField();
        inc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ind = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        outlabel = new javax.swing.JLabel();
        outa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        outb = new javax.swing.JTextField();
        outc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        outd = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("KALKULATOR MEMBANDINGKAN PECAHAN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Membandingkan dua pecahan biasa a/b dengan c/d");

        ina.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ina.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inaActionPerformed(evt);
            }
        });
        ina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inaKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("____");

        inb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inbActionPerformed(evt);
            }
        });
        inb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inbKeyTyped(evt);
            }
        });

        inc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incActionPerformed(evt);
            }
        });
        inc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                incKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("____");

        ind.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ind.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indActionPerformed(evt);
            }
        });
        ind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                indKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("dengan");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Hasilnya adalah :");

        outlabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        outlabel.setText("=");

        outa.setEditable(false);
        outa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        outa.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("____");

        outb.setEditable(false);
        outb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        outb.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        outc.setEditable(false);
        outc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        outc.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("____");

        outd.setEditable(false);
        outd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        outd.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(outa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(outb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(outlabel)
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(outc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(outd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ina, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(114, 114, 114))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(inb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(ind, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ina, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(inb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ind, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(outc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(outb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(outd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(outlabel)
                        .addGap(68, 68, 68))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inaActionPerformed
        // TODO add your handling code here:
        if (ina.getText().equals("") || inb.getText().equals("") || inc.getText().equals("") || ind.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "isi semua data");
        } else {
            String teksa = ina.getText();
            double inputa = Double.parseDouble(teksa);
            String teksb = inb.getText();
            double inputb = Double.parseDouble(teksb);
            String teksc = inc.getText();
            double inputc = Double.parseDouble(teksc);
            String teksd = ind.getText();
            double inputd = Double.parseDouble(teksd);
            //mencari kpk
            double kpk = 0;
            for (int x = 1; x <= inputd; x++) {
                kpk = (kpk + inputb);
                if (kpk % inputd == 0) {
                    int intkpk = (int) kpk;
                    String tekskpk = String.valueOf(intkpk);
                    outb.setText(tekskpk);
                    outd.setText(tekskpk);
                    break;
                }
            }
            int hasila = (int) ((kpk / inputb) * inputa);
            int hasilc = (int) ((kpk / inputd) * inputc);
            String outputa = String.valueOf(hasila);
            outa.setText(outputa);
            String outputc = String.valueOf(hasilc);
            outc.setText(outputc);
            if (hasila == hasilc) {
                outlabel.setText("=");
            } else if (hasila < hasilc) {
                outlabel.setText("<");
            } else {
                outlabel.setText(">");
            }
        }
    }//GEN-LAST:event_inaActionPerformed

    private void inbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inbActionPerformed
        // TODO add your handling code here:
        if (ina.getText().equals("") || inb.getText().equals("") || inc.getText().equals("") || ind.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "isi semua data");
        } else {
            String teksa = ina.getText();
            double inputa = Double.parseDouble(teksa);
            String teksb = inb.getText();
            double inputb = Double.parseDouble(teksb);
            String teksc = inc.getText();
            double inputc = Double.parseDouble(teksc);
            String teksd = ind.getText();
            double inputd = Double.parseDouble(teksd);
            //mencari kpk
            double kpk = 0;
            for (int x = 1; x <= inputd; x++) {
                kpk = (kpk + inputb);
                if (kpk % inputd == 0) {
                    int intkpk = (int) kpk;
                    String tekskpk = String.valueOf(intkpk);
                    outb.setText(tekskpk);
                    outd.setText(tekskpk);
                    break;
                }
            }
            int hasila = (int) ((kpk / inputb) * inputa);
            int hasilc = (int) ((kpk / inputd) * inputc);
            String outputa = String.valueOf(hasila);
            outa.setText(outputa);
            String outputc = String.valueOf(hasilc);
            outc.setText(outputc);
            if (hasila == hasilc) {
                outlabel.setText("=");
            } else if (hasila < hasilc) {
                outlabel.setText("<");
            } else {
                outlabel.setText(">");
            }
        }
    }//GEN-LAST:event_inbActionPerformed

    private void indActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indActionPerformed
        // TODO add your handling code here:
        if (ina.getText().equals("") || inb.getText().equals("") || inc.getText().equals("") || ind.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "isi semua data");
        } else {
            String teksa = ina.getText();
            double inputa = Double.parseDouble(teksa);
            String teksb = inb.getText();
            double inputb = Double.parseDouble(teksb);
            String teksc = inc.getText();
            double inputc = Double.parseDouble(teksc);
            String teksd = ind.getText();
            double inputd = Double.parseDouble(teksd);
            //mencari kpk
            double kpk = 0;
            for (int x = 1; x <= inputd; x++) {
                kpk = (kpk + inputb);
                if (kpk % inputd == 0) {
                    int intkpk = (int) kpk;
                    String tekskpk = String.valueOf(intkpk);
                    outb.setText(tekskpk);
                    outd.setText(tekskpk);
                    break;
                }
            }
            int hasila = (int) ((kpk / inputb) * inputa);
            int hasilc = (int) ((kpk / inputd) * inputc);
            String outputa = String.valueOf(hasila);
            outa.setText(outputa);
            String outputc = String.valueOf(hasilc);
            outc.setText(outputc);
            if (hasila == hasilc) {
                outlabel.setText("=");
            } else if (hasila < hasilc) {
                outlabel.setText("<");
            } else {
                outlabel.setText(">");
            }
        }
    }//GEN-LAST:event_indActionPerformed

    private void incActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incActionPerformed
        // TODO add your handling code here:
        if (ina.getText().equals("") || inb.getText().equals("") || inc.getText().equals("") || ind.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "isi semua data");
        } else {
            String teksa = ina.getText();
            double inputa = Double.parseDouble(teksa);
            String teksb = inb.getText();
            double inputb = Double.parseDouble(teksb);
            String teksc = inc.getText();
            double inputc = Double.parseDouble(teksc);
            String teksd = ind.getText();
            double inputd = Double.parseDouble(teksd);
            //mencari kpk
            double kpk = 0;
            for (int x = 1; x <= inputd; x++) {
                kpk = (kpk + inputb);
                if (kpk % inputd == 0) {
                    int intkpk = (int) kpk;
                    String tekskpk = String.valueOf(intkpk);
                    outb.setText(tekskpk);
                    outd.setText(tekskpk);
                    break;
                }
            }
            int hasila = (int) ((kpk / inputb) * inputa);
            int hasilc = (int) ((kpk / inputd) * inputc);
            String outputa = String.valueOf(hasila);
            outa.setText(outputa);
            String outputc = String.valueOf(hasilc);
            outc.setText(outputc);
            if (hasila == hasilc) {
                outlabel.setText("=");
            } else if (hasila < hasilc) {
                outlabel.setText("<");
            } else {
                outlabel.setText(">");
            }
        }
    }//GEN-LAST:event_incActionPerformed

    private void inaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inaKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) ))) {
            evt.consume();
        }
    }//GEN-LAST:event_inaKeyTyped

    private void inbKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inbKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) ))) {
            evt.consume();
        }
    }//GEN-LAST:event_inbKeyTyped

    private void incKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_incKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) ))) {
            evt.consume();
        }
    }//GEN-LAST:event_incKeyTyped

    private void indKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_indKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) ))) {
            evt.consume();
        }
    }//GEN-LAST:event_indKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Framebanpecah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Framebanpecah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Framebanpecah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Framebanpecah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Framebanpecah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ina;
    private javax.swing.JTextField inb;
    private javax.swing.JTextField inc;
    private javax.swing.JTextField ind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField outa;
    private javax.swing.JTextField outb;
    private javax.swing.JTextField outc;
    private javax.swing.JTextField outd;
    private javax.swing.JLabel outlabel;
    // End of variables declaration//GEN-END:variables
}
